services:
  web:
    build: .
    depends_on:
      - postgres
      - web-migration
    env_file:
      - .env
    ports:
      - 8123:8000
  web-migration:
    build: .
    command: npx prisma migrate deploy
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: kinnema
      POSTGRES_DB: kinnema
      POSTGRES_PASSWORD: kinnema
    ports:
      - 5432:5432