services:
  web:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 8123:8000

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: kinnema
      POSTGRES_DB: kinnema
      POSTGRES_PASSWORD: kinnema
    ports:
      - 5432:5432